PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS USERS(
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(10) NOT NULL UNIQUE,
    PASSWORD VARCHAR NOT NULL
);


CREATE TABLE IF NOT EXISTS GOALS (
    GOAL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    GOAL_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
--    TARGET_FREQUENCY TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HABIT_LOGS (
    LOG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GOAL_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    COMPLETED_DATE DATE NOT NULL DEFAULT (DATE('now')),
    NOTES TEXT,
    FOREIGN KEY (GOAL_ID) REFERENCES GOALS(GOAL_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MOOD_OPTIONS (
    MOOD_OPTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MOOD_LEVEL INTEGER CHECK (MOOD_LEVEL BETWEEN 1 AND 5),
    MOOD_LABEL TEXT,
    EMOJI TEXT
);

--INSERT INTO MOOD_OPTIONS (MOOD_LEVEL, MOOD_LABEL, EMOJI) VALUES
--    (1, 'terrible', '😥'),
--    (2, 'bad', '😞'),
--    (3, 'okay', '😐'),
--    (4, 'good', '🙂'),
--    (5, 'great', '😊');

CREATE TABLE IF NOT EXISTS DAILY_MOOD (
    MOOD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MOOD_DATE DATE NOT NULL DEFAULT (DATE('now')),
    MOOD_OPTION_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (MOOD_OPTION_ID) REFERENCES MOOD_OPTIONS(MOOD_OPTION_ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, MOOD_ID)
);

CREATE TABLE IF NOT EXISTS EMOTIONS_OPTIONS (
    OPTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMOTION_NAME TEXT NOT NULL,
    EMOJI TEXT
);

--INSERT INTO EMOTIONS_OPTIONS (EMOTION_NAME, EMOJI) VALUES
--    ('sad', '🙁'),
--    ('tired', '🥱'),
--    ('relaxed', '😌'),
--    ('happy', '😄'),
--    ('anxious', '😥'),
--    ('excited', '🤩'),
--    ('overwhelmed', '😣'),
--    ('lost', '🤨'),
--    ('mad', '😠'),
--    ('scared', '😰'),
--    ('productive', '🤓'),
--    ('embarrassed','😳'),
--    ('sick','🤒'),
--    ('risky','😏'),
--    ('annoyed','😒'),
--    ('calm','😐'),
--    ('not sure','😶');

CREATE TABLE IF NOT EXISTS DAILY_EMOTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MOOD_ID INTEGER NOT NULL,
    OPTION_ID INTEGER NOT NULL,
    SELECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (MOOD_ID) REFERENCES DAILY_MOOD(MOOD_ID) ON DELETE CASCADE,
    FOREIGN KEY (OPTION_ID) REFERENCES EMOTIONS_OPTIONS(OPTION_ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, OPTION_ID)
);

--CREATE TABLE IF NOT EXISTS JOURNALS (
--    ENTRY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
--    USER_ID INTEGER NOT NULL,
--    ENTRY_DATE DATE NOT NULL DEFAULT (DATE('now')) ,
--    CONTENT TEXT NOT NULL,
--    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
--);